### ISSUE TITLE
[db] A CI job to run alembic migrations would be useful

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-api#140]
Following up on #112 (more specifically https://github.com/pyronear/pyro-api/pull/112#discussion_r584346620), we need to automate the alembic migration whenever it needs to be run. Depending on the integration, Github Workflow could help with that!

**Comment by jeanpasquier75** [comment]
Just a draft for a new github action, no idea if it works. Questions: 
* is it okay running the job within the VM and not in a container ? 
* the job runs the `upgrade` migration method, need a process to rollback running the `downgrade` (eg connecting to db directly and running `alembic downgrade -1`) or a new migration with fixes (as `upgrade`) is sufficient
* storing production database URL in github secrets is feasible ?
* SUPERUSER_LOGIN and SUPERUSER_PWD should be set as well to retrieve app.config ?

```
name: dbmigration-alembic
on:
  push:
    branches: master
    paths:
      - 'src/alembic/**'
      - '!src/alembic/README.md'

jobs:
  run-migration:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run alembic migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          alembic upgrade head
```
